Final changes to clean up FFLIP

diff --git a/ffX-migrate-to-4830/files/lib/gluon/upgrade/003-ffX-to-4830 b/ffX-migrate-to-4830/files/lib/gluon/upgrade/003-ffX-to-4830
--- a/ffX-migrate-to-4830/files/lib/gluon/upgrade/003-ffX-to-4830
+++ b/ffX-migrate-to-4830/files/lib/gluon/upgrade/003-ffX-to-4830
@@ -63,6 +63,12 @@ fi
 
 if [ "$(uci get autoupdater.stable.mirror | grep firmware.*4830.org >/dev/null ; echo $?)" = "0" ]; then
  if [ ${delayed_reconf} -eq 0 ]; then
+  lat=$(uci get gluon-node-info.@location[0].latitude 2>/dev/null || echo "0.00")
+  lon=$(uci get gluon-node-info.@location[0].longitude 2>/dev/null || echo "0.00")
+  if [ "${lat}" = "0.00" -o "${lon}" = "0.00" ]; then
+   echo "Started WiFi-based location gathering in the backgroud due to missing coordinates." | tee -a /root/multidomain-migration.log
+   ((sleep 150 ; /lib/gluon/ffgt-geolocate/geolocate-lite.sh force ; echo >>/root/multidomain-migration.log "Geolocation results:" ; cat /tmp/geoloc.out >>/root/multidomain-migration.log) &)
+  fi
   logger "4830.org FW detected! Move on, nothing to see here!"
   echo "4830.org FW detected! Move on, nothing to see here!" | tee -a /root/multidomain-migration.log
   rm ${LOCKFILE}
@@ -99,16 +105,16 @@ if [ "$(uci get autoupdater.stable.mirror | grep freifunk-lippe.de >/dev/null ; 
   domain="lem"
  fi
  targetlocode="$(/lib/gluon/ffgt-geolocate/is_mns.sh)"
- if [ "${targetlocode}" = "mns" ]; then
+ if [ "${targetlocode}" != "zzz" ]; then
   uci set autoupdater.settings.branch='mns'
   uci commit autoupdater
-  echo "Moved mns node to autoupdate branch mns." | tee -a /root/multidomain-migration.log
+  echo "Moved ${targetlocode} node to autoupdate branch mns." | tee -a /root/multidomain-migration.log
  fi
  lat=$(uci get gluon-node-info.@location[0].latitude 2>/dev/null || echo "0.00")
  lon=$(uci get gluon-node-info.@location[0].longitude 2>/dev/null || echo "0.00")
  if [ "${lat}" = "0.00" -o "${lon}" = "0.00" ]; then
   echo "Started WiFi-based location gathering in the backgroud due to missing coordinates." | tee -a /root/multidomain-migration.log
-  ((sleep 150 ; /lib/gluon/ffgt-geolocate/geolocate-lite.sh force ; uci set gluon-node-info.@location[0].share_location=0 ; echo >>/root/multidomain-migration.log "Geolocation results:" ; cat /tmp/geoloc.out >>/root/multidomain-migration.log) &)
+  ((sleep 150 ; /lib/gluon/ffgt-geolocate/geolocate-lite.sh force ; echo >>/root/multidomain-migration.log "Geolocation results:" ; cat /tmp/geoloc.out >>/root/multidomain-migration.log) &)
  fi
  echo "Migrating FFLIP-FW, mesh ${olddom}, to 4830.org's ${domain} ..." | tee -a /root/multidomain-migration.log
 elif [ ${delayed_reconf} -eq 1 ]; then
